#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
python3 << END
import sys
import os 
import psycopg2
try:
    print(f"Attempting to connect to PostgreSQL at {os.environ.get('PG_HOST')}:{os.environ.get('PG_PORT')}")
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}",
    )
except psycopg2.OperationalError as e:
    print(f"Error connecting to PostgreSQL: {e}")
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
  >&2 echo "Waiting for PostgreSQL to become available...:-("
  sleep 5
done
>&2 echo "PostgreSQL is ready!!! ... :-)"

exec "$@"